/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FAQ { 'question' : string, 'answer' : string }
export interface Testimonial { 'name' : string, 'quote' : string }
export interface _SERVICE {
  'addFAQ' : ActorMethod<[string, string], undefined>,
  'addTestimonial' : ActorMethod<[string, string], undefined>,
  'addWaitlistEntry' : ActorMethod<[string, string], undefined>,
  'getAllFAQs' : ActorMethod<[], Array<FAQ>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getWaitlistCount' : ActorMethod<[], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];