/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
export const Testimonial = IDL.Record({
  'name' : IDL.Text,
  'quote' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFAQ' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addWaitlistEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getWaitlistCount' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const Testimonial = IDL.Record({ 'name' : IDL.Text, 'quote' : IDL.Text });
  
  return IDL.Service({
    'addFAQ' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addWaitlistEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getWaitlistCount' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };